/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RdslUiModule extends org.xtext.ui.AbstractRdslUiModule {
	public RdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
