/*
 * generated by Xtext
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.RdslGrammarAccess;

@SuppressWarnings("all")
public class RdslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RdslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Imports_ExternalKeyword_1_q;
	protected AbstractElementAlias match_importVariable_OptionalKeyword_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RdslGrammarAccess) access;
		match_Imports_ExternalKeyword_1_q = new TokenAlias(false, true, grammarAccess.getImportsAccess().getExternalKeyword_1());
		match_importVariable_OptionalKeyword_1_q = new TokenAlias(false, true, grammarAccess.getImportVariableAccess().getOptionalKeyword_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Imports_ExternalKeyword_1_q.equals(syntax))
				emit_Imports_ExternalKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_importVariable_OptionalKeyword_1_q.equals(syntax))
				emit_importVariable_OptionalKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'external'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'imports:' (ambiguity) imported=importVariable
	 *     (rule start) 'imports:' (ambiguity) imports+=importVariable
	 */
	protected void emit_Imports_ExternalKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '(optional)'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_importVariable_OptionalKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
